from collections import Counter

from scripts.seeder import simulator
from scripts.seeder.__main__ import CustomerState
from scripts.seeder.run_log import format_event, format_run_log


def _state(sim_id: str, *, tier="standard", cadence="month", state="active") -> CustomerState:
    return CustomerState(
        sim_id=sim_id,
        stripe_customer_id=f"cus_{sim_id}",
        sub_id=f"sub_{sim_id}",
        clock_id=f"clk_{sim_id}",
        clock_day=180,
        current_tier=tier,
        current_cadence=cadence,
        current_state=state,
    )


def _ev(sim_id: str, day: int, type_: str, **payload) -> simulator.Event:
    return simulator.Event(day=day, sim_id=sim_id, type=type_, payload=payload)


# ---------------------------------------------------------------------------
# format_event
# ---------------------------------------------------------------------------

def testformat_event_customer_created_monthly():
    ev = _ev("sim_1", 0, "customer_created", tier="standard", cadence="month")
    assert format_event(ev) == "customer_created (standard, monthly)"


def testformat_event_customer_created_yearly():
    ev = _ev("sim_1", 0, "customer_created", tier="engage", cadence="year")
    assert format_event(ev) == "customer_created (engage, yearly)"


def testformat_event_tier_upgraded():
    ev = _ev("sim_1", 47, "tier_upgraded", **{"from": "standard", "to": "pro_plus"})
    assert format_event(ev) == "tier_upgraded (standard → pro_plus)"


def testformat_event_tier_downgraded():
    ev = _ev("sim_1", 47, "tier_downgraded", **{"from": "pro_plus", "to": "standard"})
    assert format_event(ev) == "tier_downgraded (pro_plus → standard)"


def testformat_event_bare_status_events():
    assert format_event(_ev("sim_1", 60, "marked_past_due")) == "marked_past_due"
    assert format_event(_ev("sim_1", 70, "canceled")) == "canceled"
    assert format_event(_ev("sim_1", 80, "recovered")) == "recovered"


# ---------------------------------------------------------------------------
# format_run_log — header
# ---------------------------------------------------------------------------

def _minimal_log(**overrides) -> str:
    base = dict(
        seed=42,
        sim_days=180,
        initial_count=1,
        events=[_ev("sim_1", 0, "customer_created", tier="standard", cadence="month")],
        states={"sim_1": _state("sim_1")},
        state_counts=Counter({"active": 1}),
        tier_counts=Counter({"standard": 1}),
        cadence_counts=Counter({"month": 1}),
        generated_on="2026-05-05",
    )
    base.update(overrides)
    return format_run_log(**base)


def test_log_header_line_first():
    text = _minimal_log()
    first = text.splitlines()[0]
    assert first == (
        "# Generated by scripts/seeder/__main__.py on 2026-05-05. "
        "Regenerate via 'python -m scripts.seeder'."
    )


# ---------------------------------------------------------------------------
# format_run_log — summary block
# ---------------------------------------------------------------------------

def test_summary_block_basic_fields():
    text = _minimal_log(seed=7, sim_days=90, initial_count=3,
                        states={f"sim_{i}": _state(f"sim_{i}") for i in (1, 2, 3, 4)})
    assert "Seed: 7" in text
    assert "Simulation days: 90" in text
    assert "Initial customers: 3" in text
    assert "Final customer count: 4" in text


def test_summary_state_distribution_sorted_alphabetically():
    text = _minimal_log(
        states={f"sim_{i}": _state(f"sim_{i}") for i in (1, 2, 3)},
        state_counts=Counter({"past_due": 1, "active": 2}),
    )
    section = text.split("Final state distribution:")[1].split("\n\n")[0]
    lines = [ln for ln in section.splitlines() if ln.strip()]
    # Sorted alphabetically: active before past_due
    assert lines[0].lstrip().startswith("active:")
    assert lines[1].lstrip().startswith("past_due:")
    assert "2" in lines[0]
    assert "1" in lines[1]


def test_summary_active_tier_distribution_with_percent():
    text = _minimal_log(
        tier_counts=Counter({"standard": 30, "pro_plus": 14, "engage": 8, "enterprise": 6}),
    )
    section = text.split("Final active-tier distribution:")[1].split("\n\n")[0]
    # 30 / 58 = 51.7%, 14/58 = 24.1%, 8/58 = 13.8%, 6/58 = 10.3%
    assert "(51.7%)" in section
    assert "(24.1%)" in section
    assert "(13.8%)" in section
    assert "(10.3%)" in section


def test_summary_active_cadence_translates_month_year_to_words():
    text = _minimal_log(
        cadence_counts=Counter({"month": 49, "year": 9}),
    )
    section = text.split("Final active-cadence distribution:")[1].split("\n\n")[0]
    assert "monthly:" in section
    assert "yearly:" in section
    # 49/58 = 84.5%, 9/58 = 15.5%
    assert "(84.5%)" in section
    assert "(15.5%)" in section


# ---------------------------------------------------------------------------
# format_run_log — per-customer blocks
# ---------------------------------------------------------------------------

def test_per_customer_block_creation_only_emits_no_further_events_line():
    text = _minimal_log()
    assert "─── sim_1  cus_sim_1  sub_sim_1 ───" in text
    assert "day   0: customer_created (standard, monthly)" in text
    assert "(no further events)" in text


def test_per_customer_block_with_upgrade_and_cancel():
    events = [
        _ev("sim_1", 0, "customer_created", tier="standard", cadence="month"),
        _ev("sim_1", 47, "tier_upgraded", **{"from": "standard", "to": "pro_plus"}),
        _ev("sim_1", 102, "canceled"),
    ]
    text = _minimal_log(events=events)
    assert "day   0: customer_created (standard, monthly)" in text
    assert "day  47: tier_upgraded (standard → pro_plus)" in text
    assert "day 102: canceled" in text
    assert "(no further events)" not in text


def test_per_customer_block_includes_stripe_ids_in_header():
    states = {
        "sim_1": CustomerState(
            sim_id="sim_1",
            stripe_customer_id="cus_ABC123",
            sub_id="sub_XYZ789",
            clock_id="clk_1",
            clock_day=180,
            current_tier="standard",
            current_cadence="month",
            current_state="active",
        )
    }
    text = _minimal_log(states=states)
    assert "─── sim_1  cus_ABC123  sub_XYZ789 ───" in text


def test_customers_sorted_by_numeric_suffix_not_lexicographically():
    """Regression: string sort produces sim_1, sim_10, sim_2, sim_20 — looks broken."""
    sim_ids = ["sim_1", "sim_2", "sim_10", "sim_20"]
    states = {sid: _state(sid) for sid in sim_ids}
    events = [_ev(sid, 0, "customer_created", tier="standard", cadence="month") for sid in sim_ids]
    text = _minimal_log(states=states, events=events, initial_count=4)

    positions = [text.index(f"─── {sid}  ") for sid in sim_ids]
    # Block for sim_1 must come before sim_2, which must come before sim_10, which before sim_20.
    assert positions == sorted(positions), (
        f"Expected numeric sort sim_1 < sim_2 < sim_10 < sim_20, got positions {positions}"
    )
