"""Formats the seeder run summary and per-customer event timeline as a
human-readable text file. Pure formatter — no Stripe calls, no file I/O.
Output is written to output/seeder_events.txt by the orchestrator.
"""
from __future__ import annotations

from collections import Counter, defaultdict
from typing import TYPE_CHECKING

from . import simulator

if TYPE_CHECKING:
    from .__main__ import CustomerState


_CADENCE_WORD = {"month": "monthly", "year": "yearly"}


def format_event(event: simulator.Event) -> str:
    """Render a single simulator event as 'event_type (details)' — no day prefix."""
    if event.type == "customer_created":
        cadence = event.payload["cadence"]
        return (
            f"customer_created ({event.payload['tier']}, "
            f"{_CADENCE_WORD.get(cadence, cadence)})"
        )
    if event.type in ("tier_upgraded", "tier_downgraded"):
        return f"{event.type} ({event.payload['from']} → {event.payload['to']})"
    return event.type


def format_distribution(
    label: str,
    counts: Counter,
    *,
    with_percent: bool = False,
    key_translate: dict | None = None,
) -> str:
    items = [
        ((key_translate or {}).get(k, k), v) for k, v in counts.items()
    ]
    items.sort(key=lambda kv: kv[0])
    lines = [f"{label}:"]
    if not items:
        return lines[0]
    key_width = max(len(k) for k, _ in items) + 1   # +1 for the trailing colon
    val_width = max(len(str(v)) for _, v in items)
    total = sum(v for _, v in items)
    for k, v in items:
        prefix = f"  {k + ':':<{key_width}} {v:>{val_width}}"
        if with_percent:
            pct = (v / total * 100) if total else 0.0
            lines.append(f"{prefix} ({pct:.1f}%)")
        else:
            lines.append(prefix)
    return "\n".join(lines)


def _sim_id_sort_key(sim_id: str) -> int:
    """Sort sim_1, sim_2, sim_10 numerically — string sort would break order."""
    return int(sim_id.split("_")[1])


def format_run_log(
    *,
    seed: int,
    sim_days: int,
    initial_count: int,
    events: list[simulator.Event],
    states: dict[str, CustomerState],
    state_counts: Counter,
    tier_counts: Counter,
    cadence_counts: Counter,
    generated_on: str,
    skips: dict[int, str] | None = None,
) -> str:
    parts: list[str] = []
    parts.append(
        f"# Generated by scripts/seeder/__main__.py on {generated_on}. "
        "Regenerate via 'python -m scripts.seeder'."
    )
    parts.append("")
    parts.append("SEEDER RUN")
    parts.append(f"Seed: {seed}")
    parts.append(f"Simulation days: {sim_days}")
    parts.append(f"Initial customers: {initial_count}")
    parts.append("")
    parts.append(f"Final customer count: {len(states)}")
    parts.append(format_distribution("Final state distribution", state_counts))
    parts.append("")
    parts.append(format_distribution(
        "Final active-tier distribution", tier_counts, with_percent=True,
    ))
    parts.append("")
    parts.append(format_distribution(
        "Final active-cadence distribution",
        cadence_counts,
        with_percent=True,
        key_translate=_CADENCE_WORD,
    ))
    parts.append("")
    parts.append("═" * 70)
    parts.append("")

    events_by_sim = defaultdict(list)
    for i, ev in enumerate(events):
        events_by_sim[ev.sim_id].append((i, ev))

    skips = skips or {}
    for state in sorted(states.values(), key=lambda s: _sim_id_sort_key(s.sim_id)):
        parts.append(
            f"─── {state.sim_id}  {state.stripe_customer_id}  {state.sub_id} ───"
        )
        cust_events = sorted(events_by_sim.get(state.sim_id, []), key=lambda ie: ie[1].day)
        for idx, ev in cust_events:
            line = f"day {ev.day:>3}: {format_event(ev)}"
            if idx in skips:
                line += f"  (skipped: {skips[idx]})"
            parts.append(line)
        if len(cust_events) <= 1:
            parts.append("(no further events)")
        parts.append("")

    return "\n".join(parts)
